export { default as capitalize } from "./capitalize.js";
export { default as convertQualityScoreToLetter } from "./convert-quality-score-to-letter.js";
export { default as convertQualityScoreToAvatar } from "./convert-quality-score-to-avatar.jsx";
export { default as createEpicPlan } from "./create-epic-plan.js";
export { default as dayjsLocalizer } from "./dayjs-localizer.js";
export { default as dayjs } from "./dayjs.js";
export { default as filterOutliers } from "./filter-outliers.js";
export { default as getColorForQualityScore } from "./get-color-for-quality-score.js";
export { default as getRepoUrl } from "./get-repo-url.js";
export { default as isFuzzyMatch } from "./is-fuzzy-match.js";
export { default as jwt } from "./jwt.js";
export { default as metricsInfo } from "./metrics-info.js";
export { generalMetricOptions, allMetricOptions, systemChecksOptions } from "./general-metric-options.js";
export { default as overridePlotlyButtons } from "./override-plotly-buttons.js";
export { default as percentChange } from "./percent-change.js";
export { default as qualityCell } from "./quality-cell.jsx";
export { default as ProjectQualityGatesCell } from "./name-cell.jsx";
export { default as sum } from "./sum.js";
export { default as taskIsSearchMatch } from "./task-is-search-match.js";
export { default as useLocalStorage } from "./use-local-storage.js";
export { default as useSnackbar, snackStore } from "./use-snackbar.js";
export { default as parseRepo } from "./parse-repo.js";
export { default as getWorkdayTime } from "./get-workday-time.js";
export { default as round } from "./round.js";
export { default as useDocumentTitle } from "./use-document-title.js";
export { default as useKeysForSuggestions } from "./get-keys-for-suggestions.js";
export * from "./tour-steps/index.js";
export { default as prettyMilliseconds } from "./pretty-milliseconds.js";
export { default as sortAndPrioritizeBranches } from "./sort-and-prioritize-branches.js";
export { default as formatTileNumber } from "./format-tile-number.js";
export { default as useOutsideClick } from "./use-outside-click.jsx";
export { default as setRepositoryBranches } from "./set-repository-branches.js";
export { default as QualityGates } from "./quality-gates/index.js";
export { default as OverviewInfo } from "./overview-info/index.js";
export { default as constructCommitHref } from "./construct-commit-href.js";
export { default as createRepositoryName } from "./create-repository-name.js";
export { default as createNavigationTabsConfig } from "./create-navigation-tabs-config.js";
export { AcceptedFormatsComponent } from "./get-accepted-repo-url.jsx";
export { constructMessage, constructCharacteristicsMessage } from "./construct-overview-section-messages.js";
export { default as formatLocalNumber } from "./format-local-number.js";
export * from "./developer-stats/index.js";
export { default as ROUTE_PATTERNS } from "./route-patterns.js";
export const POSSIBLE_COLUMNS = new Map([
	["none", ["Open", "Closed"]],
	["minimal", ["To Do", "In Progress", "Done"]],
	["default", ["Backlog", "Sprint Planning", "In Progress", "Delivered", "Accepted"]],
]);
export const POSSIBLE_NOTIFICATIONS_DAYS = new Set(["never", "1 day before", "2 days before", "3 days before", "1 week before"]);
export const POSSIBLE_PRIORITIES = new Set(["none", "low", "medium", "high"]);
export const POSSIBLE_VULNERABILITIES_SEVERITY = new Set(["low", "moderate", "high", "critical"]);
export const POSSIBLE_VIOLATIONS_SEVERITY = new Set(["Critical", "Major", "Minor"]);
export const POSSIBLE_LANGUAGES = new Set(["JavaScript", "TypeScript", "Java", "C#", "Python", "PHP", "Kotlin", "Dart"]);
export const DEFAULT_LABELS = new Set(["bug", "documentation", "enhancement", "feature", "design", "invalid", "duplicate"]);
export const MUTATION_DELAY_IN_MS = 500;
export const DATE_FORMAT = "D MMM, YYYY";
